Repository DEPthes/2nd-MVP-BeginVegan-Server, pull requests merged in 2023-08, with the labels that each got.

#4 [FEAT]: AccessToken을 이용한 유저 정보 조회 API 구현
  src/main/java/com/beginvegan/domain/user/application/UserService.java
  src/main/java/com/beginvegan/domain/user/dto/UserDetailRes.java
  src/main/java/com/beginvegan/domain/user/presentation/UserController.java
Labels: feature

#11 [FEAT]: ERD 수정 사항 반영
  .gitignore
  src/main/java/com/beginvegan/domain/block/domain/Block.java
  src/main/java/com/beginvegan/domain/restaurant/domain/Restaurant.java
Labels: feature, fix

#13 [CHORE]: OneToMany -> new ArrayList<> 추가
  src/main/java/com/beginvegan/domain/auth/domain/Token.java
  src/main/java/com/beginvegan/domain/food/domain/Food.java
  src/main/java/com/beginvegan/domain/magazine/domain/Magazine.java
  src/main/java/com/beginvegan/domain/restaurant/domain/Restaurant.java
Labels: chore

#18 [FEAT]: 레시피 탭 레시피 목록 조회 API 구현
  src/main/java/com/beginvegan/domain/food/application/FoodService.java
  src/main/java/com/beginvegan/domain/food/dto/FoodIngredientDto.java
  src/main/java/com/beginvegan/domain/food/dto/FoodRecipeListRes.java
  src/main/java/com/beginvegan/domain/food/presentation/FoodController.java
Labels: feature

#20 [FEAT]: 레시피 상세 조회 API 구현
  src/main/java/com/beginvegan/domain/block/domain/Block.java
  src/main/java/com/beginvegan/domain/block/dto/BlockDto.java
  src/main/java/com/beginvegan/domain/food/application/FoodService.java
  src/main/java/com/beginvegan/domain/food/dto/FoodIngredientDto.java
  src/main/java/com/beginvegan/domain/food/dto/request/FoodDetailReq.java
  src/main/java/com/beginvegan/domain/food/dto/response/FoodDetailRes.java
  src/main/java/com/beginvegan/domain/food/exception/FoodNotFoundException.java
  src/main/java/com/beginvegan/domain/food/presentation/FoodController.java
Labels: feature

#22 [FEAT]: 메인 페이지 3가지 랜덤 음식 목록 조회 API 구현
  src/main/java/com/beginvegan/domain/food/application/FoodService.java
  src/main/java/com/beginvegan/domain/food/dto/response/FoodListRes.java
  src/main/java/com/beginvegan/domain/food/presentation/FoodController.java
Labels: feature

#27 [FEAT]: 메인 화면 매거진 목록 중 2가지 랜덤 조회 API 구현
  src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java
  src/main/java/com/beginvegan/domain/magazine/domain/Magazine.java
  src/main/java/com/beginvegan/domain/magazine/domain/MagazineType.java
  src/main/java/com/beginvegan/domain/magazine/domain/repository/MagazineRepository.java
  src/main/java/com/beginvegan/domain/magazine/dto/response/MagazineListRes.java
  src/main/java/com/beginvegan/domain/magazine/presentation/MagazineController.java
Labels: feature

#30 [FEAT]: sign-out api 추가
  src/main/java/com/beginvegan/domain/auth/application/AuthService.java
  src/main/java/com/beginvegan/domain/auth/dto/RefreshTokenReq.java
  src/main/java/com/beginvegan/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/beginvegan/domain/auth/presentation/AuthController.java
Labels: feature

#32 [FEAT]: 프로필 API 구현
  src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java
  src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/com/beginvegan/domain/bookmark/dto/BookmarkListRes.java
  src/main/java/com/beginvegan/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/beginvegan/domain/restaurant/dto/RestaurantDetailRes.java
  src/main/java/com/beginvegan/domain/review/application/ReviewService.java
  src/main/java/com/beginvegan/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/beginvegan/domain/review/dto/ReviewDetailRes.java
  src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java
  src/main/java/com/beginvegan/domain/user/application/UserService.java
  src/main/java/com/beginvegan/domain/user/domain/User.java
  src/main/java/com/beginvegan/domain/user/dto/UpdateMarketingConsentReq.java
  src/main/java/com/beginvegan/domain/user/dto/UserDetailRes.java
  src/main/java/com/beginvegan/domain/user/presentation/UserController.java
Labels: feature

#33 [RELEASE]: develop -> main Merge
  .github/workflows/deploy.yml
  src/main/java/com/beginvegan/domain/auth/application/AuthService.java
  src/main/java/com/beginvegan/domain/auth/dto/RefreshTokenReq.java
  src/main/java/com/beginvegan/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/beginvegan/domain/auth/presentation/AuthController.java
  src/main/java/com/beginvegan/domain/block/domain/Block.java
  src/main/java/com/beginvegan/domain/block/dto/BlockDto.java
  src/main/java/com/beginvegan/domain/bookmark/application/BookmarkService.java
  src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/com/beginvegan/domain/bookmark/dto/BookmarkListRes.java
  src/main/java/com/beginvegan/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/beginvegan/domain/food/application/FoodService.java
  src/main/java/com/beginvegan/domain/food/dto/FoodIngredientDto.java
  src/main/java/com/beginvegan/domain/food/dto/request/FoodDetailReq.java
  src/main/java/com/beginvegan/domain/food/dto/response/FoodDetailRes.java
  src/main/java/com/beginvegan/domain/food/dto/response/FoodListRes.java
  src/main/java/com/beginvegan/domain/food/dto/response/FoodRecipeListRes.java
  src/main/java/com/beginvegan/domain/food/exception/FoodNotFoundException.java
  src/main/java/com/beginvegan/domain/food/presentation/FoodController.java
  src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java
  src/main/java/com/beginvegan/domain/magazine/domain/Magazine.java
  src/main/java/com/beginvegan/domain/magazine/domain/MagazineType.java
  src/main/java/com/beginvegan/domain/magazine/domain/repository/MagazineRepository.java
  src/main/java/com/beginvegan/domain/magazine/dto/response/MagazineListRes.java
  src/main/java/com/beginvegan/domain/magazine/presentation/MagazineController.java
  src/main/java/com/beginvegan/domain/restaurant/dto/RestaurantDetailRes.java
  src/main/java/com/beginvegan/domain/review/application/ReviewService.java
  src/main/java/com/beginvegan/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/beginvegan/domain/review/dto/ReviewDetailRes.java
  src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java
  src/main/java/com/beginvegan/domain/user/application/UserService.java
  src/main/java/com/beginvegan/domain/user/domain/User.java
  src/main/java/com/beginvegan/domain/user/dto/UpdateMarketingConsentReq.java
  src/main/java/com/beginvegan/domain/user/dto/UpdateVeganTypeReq.java
  src/main/java/com/beginvegan/domain/user/dto/UserDetailRes.java
  src/main/java/com/beginvegan/domain/user/exception/InvalidUserException.java
  src/main/java/com/beginvegan/domain/user/presentation/UserController.java
Labels: release

#35 [FEAT]: 리뷰 등록 API 구현
  src/main/java/com/beginvegan/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/beginvegan/domain/restaurant/exception/InvalidRestaurantException.java
  src/main/java/com/beginvegan/domain/review/application/ReviewService.java
  src/main/java/com/beginvegan/domain/review/dto/PostReviewReq.java
  src/main/java/com/beginvegan/domain/review/dto/ReviewListRes.java
  src/main/java/com/beginvegan/domain/review/presentation/ReviewController.java
Labels: feature

#37 [FEAT]: 매거진 상세조회 API 구현
  src/main/java/com/beginvegan/domain/block/domain/Block.java
  src/main/java/com/beginvegan/domain/block/domain/BlockType.java
  src/main/java/com/beginvegan/domain/block/dto/BlockDto.java
  src/main/java/com/beginvegan/domain/food/application/FoodService.java
  src/main/java/com/beginvegan/domain/food/domain/Food.java
  src/main/java/com/beginvegan/domain/food/dto/response/FoodDetailRes.java
  src/main/java/com/beginvegan/domain/magazine/application/MagazineService.java
  src/main/java/com/beginvegan/domain/magazine/domain/Magazine.java
  src/main/java/com/beginvegan/domain/magazine/dto/request/MagazineDetailReq.java
  src/main/java/com/beginvegan/domain/magazine/dto/response/MagazineDetailRes.java
  src/main/java/com/beginvegan/domain/magazine/exception/MagazineNotFoundException.java
  src/main/java/com/beginvegan/domain/magazine/presentation/MagazineController.java
Labels: feature

#38 [FEAT]: 식당/카페 상세 정보(메뉴까지) 조회 API 구현
  src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java
  src/main/java/com/beginvegan/domain/restaurant/domain/Restaurant.java
  src/main/java/com/beginvegan/domain/restaurant/domain/repository/RestaurantRepository.java
  src/main/java/com/beginvegan/domain/restaurant/dto/MenuDetailRes.java
  src/main/java/com/beginvegan/domain/restaurant/dto/RestaurantAndMenusRes.java
  src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java
  src/main/java/com/beginvegan/domain/review/domain/repository/ReviewRepository.java
  src/main/java/com/beginvegan/domain/review/dto/RestaurantReviewDetailRes.java
  src/main/java/com/beginvegan/domain/review/dto/ReviewListRes.java
Labels: feature

#43 [FEAT]: 식당/카페 스크랩 삭제 API 구현
  src/main/java/com/beginvegan/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/com/beginvegan/domain/bookmark/exception/NotExistsBookmarkException.java
  src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java
  src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java
Labels: feature

#50 [FEAT]: 주변 식당 목록 조회 api
  src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java
  src/main/java/com/beginvegan/domain/restaurant/dto/ArroundRestaurantListRes.java
  src/main/java/com/beginvegan/domain/restaurant/dto/MenuDto.java
  src/main/java/com/beginvegan/domain/restaurant/dto/request/LocationReq.java
  src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java
Labels: feature

#55 [FIX]: 주변 식당 조회 api 요청 값 식당 id -> 사용자 위치 위도, 경도 변경
  src/main/java/com/beginvegan/domain/restaurant/application/RestaurantService.java
  src/main/java/com/beginvegan/domain/restaurant/presentation/RestaurantController.java
Labels: fix
